### 기업 목록 조회 라우터 연결 테스트
GET http://localhost:3000/api/companies

### 기업 목록 조회 페이지네이션
GET http://localhost:3000/api/companies?page=1&pageSize=5

### 기업명 검색
GET http://localhost:3000/api/companies?keyword=퍼블리카

### 누적 투자금액 낮은순
GET http://localhost:3000/api/companies?sort=investmentAsc

### 잘못된 sort
GET http://localhost:3000/api/companies?sort=wrong

### 기업 상세 조회
GET http://localhost:3000/api/companies/f8q2mz

### 기업 상세 조회 실패 - id 형식 오류
GET http://localhost:3000/api/companies/zzzzzz

### 기업 상세 조회 실패 - 잘못된 메서드
POST http://localhost:3000/api/companies/f8q2mz
Content-Type: application/json

{}

### 기업별 투자 목록 조회
GET http://localhost:3000/api/companies/m9v5jx/investments

### 기업별 투자 목록 페이지네이션
GET http://localhost:3000/api/companies/f8q2mz/investments?page=1&pageSize=5

### 기업별 투자 목록 잘못된 page
GET http://localhost:3000/api/companies/f8q2mz/investments?page=abc


### 투자 현황 조회
GET http://localhost:3000/api/companies/investmentStatus

###

### 투자 현황 조회 - 페이지 변경
GET http://localhost:3000/api/companies/investmentStatus?page=2&pageSize=5

###

### 투자 현황 조회 - 실제 투자금 높은순
GET http://localhost:3000/api/companies/investmentStatus?orderBy=actualInvestmentAmount&order=desc

###

### 투자 현황 조회 - View My Startup 투자금 낮은순
GET http://localhost:3000/api/companies/investmentStatus?orderBy=userInvestmentAmount&order=asc

###

### 투자 현황 조회 - 잘못된 page
GET http://localhost:3000/api/companies/investmentStatus?page=abc

###

### 투자 현황 조회 - 잘못된 order
GET http://localhost:3000/api/companies/investmentStatus?order=banana

###

### 투자 현황 조회 - 잘못된 orderBy
GET http://localhost:3000/api/companies/investmentStatus?orderBy=test